### ISSUE TITLE
Scroll lock icon shows as white square in lock state.

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-components#68]

**Comment by patrickelectric** [comment]
![image](https://user-images.githubusercontent.com/1215497/38891293-4d7eb624-425a-11e8-8de5-dbab68400623.png)

**Comment by patrickelectric** [comment]
I'm unable to test it, I did an AppImage locally and this issues does not appear, it must be a problem related to ubuntu Qt version. I'll do further investigation.

**Comment by patrickelectric** [comment]
Env with windows and qt 5.9.4 replicates the problem, I'll continue with a solution from this.
