### ISSUE TITLE
Serial port selection box isn't wide enough

### ISSUE THREAD

**Issue by rjehangir** [bluerobotics/ping-components#89]
Difficult to select the proper port on here.

![image](https://user-images.githubusercontent.com/968100/38890724-0f60b8c4-4237-11e8-90be-a788990bd3db.png)

**Comment by rjehangir** [comment]
Should probably filter out ports that are definitely not right also.

**Comment by jaxxzer** [comment]
previous issue here: https://github.com/bluerobotics/ping-components/issues/23
